# Configure debug env below

debug:
  MySQL:
    host: 127.0.0.1
    port: 3306
    name: old-data-api
    username: root
    password: mypassword
    connections: 60
    idles: 10
  Redis:
    host: 127.0.0.1
    port: 6379
  RabbitMQ:
    host: 127.0.0.1
    port: 5672
    user: guest
    password: guest

release:
  MySQL:
    host: 127.0.0.1
    port: 3306
    user: root
    password: mypassword
    connections: 60
    idles: 10